###################################
## General Settings

## These settings are standard Jekyll Settings, check the Jekyll docs for help

## Preprocessor settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

## Jekyll Serve
port: 4000

## Output
siteurl:                    ## Optional 
baseurl:                    ## Optional 
destination: _site          ## Output folder


###################################
## Style Guide Shell Settings

## These settings are used in when generating the style guide shell
sg_title: Dycards Styleguide
sg_version: 3.0
sg_keywords: jekyll, style guide, playbook, design, code 
sg_author: Maximilian Hajek, Marco Venditto & Martin Sonnberger
sg_description: This Styleguide maintains design and code standards and documentation for the Dycards digital user interface.
sg_language: en
sg_styles: /styleguide/css/styleguide.css
sg_favicon: /styleguide/branding/favicon.svg
sg_ga: ## Analytics Tracking

## Generates Style Guide Shell Styles
## Enable to change the style guide shell stylesheet.
#sass: 
#  sass_dir: styleguide/_scss
#  style: :compressed


###################################
## Collection Settings

## Outputs the _docs collection !Required
collections:
  docs: 
    output: true

## Sets the default attributes for the Documentation and Pattern Files !Required
defaults:
  - 
    scope:
      path: "_docs"
    values:
      layout: doc
      type: doc
  - 
    scope:
      path: "_docs/foundations"
    values:
      layout: doc
      type: foundation
  - 
    scope:
      path: "_docs/components"
    values:
      layout: doc
      type: component   
  - 
    scope:
      path: "src/patterns"
    values:
      layout: pattern
      type: pattern
      maturity: planned
      title: Not Assigned
      styles: Not Assigned
  - 
    scope:
      path: "src/patterns/sample-pages"
    values:
      type: sample
      title: Not Assigned        

###################################
## Pattern Settings
## These attributes are applied to all patterns via the pattern.html layout.

pattern_author: Maximilian Hajek, Marco Venditto & Martin Sonnberger
pattern_description: This Styleguide maintains design and code standards and documentation for the Dycards digital user interface.        ## used in <head> tag
pattern_language: de
pattern_favicon: /src/assets/images/logo.svg
pattern_styles:                 ## add style locations here
  - /src/assets/css/style.css
pattern_scripts:                ## add script locations here
  - /src/assets/js/libs/jquery-2.1.4.min.js  


## Generates Pattern Styles
## Disable to prevent pattern styles from being generated.
sass:
  sass_dir: src/assets/_scss 
  style: :compressed      